spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/transaction_demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root

mybatis:
  type-aliases-package: com.guigu.bean
  mapper-locations: classpath:/mapper/*.xml
#logging:
#  level:
#    com:
#      guigu:
logging:
  level: debug
#        mapper: debug